--- # conditional yml sample for different flavours of linux
- hosts: testgp
  user: ansible
  become: yes
  connection: ssh
  tasks:
            - name: Installation of webserver for debian linux
              command: apt-get install apache2 -y
              when: ansible_os_family == "Debian"
              name: Installation of webserver for redhat linux
              command: yum install  httpd -y
              when: ansible_os_family == "RedHat"
              
